export const CREATE_INVOICE_SUBMITTED = "CREATE_INVOICE_SUBMITTED";
export const CREATE_INVOICE_SUCCESS = "CREATE_INVOICE_SUCCESS";
export const CREATE_INVOICE_ERROR = "CREATE_INVOICE_ERROR";
export const GET_INVOICE_SUCCESS = "GET_INVOICE_SUCCESS";
export const EDIT_INVOICE_SUCCESS = "EDIT_INVOICE_SUCCESS";
