export const CREATE_INVOICE_SUBMITTED = "CREATE_INVOICE_SUBMITTED";
export const CREATE_INVOICE_SUCCESS = "CREATE_INVOICE_SUCCESS";
export const CREATE_INVOICE_ERROR = "CREATE_INVOICE_ERROR";

export const CREATE_CUSTOMER_SUBMITTED = "CREATE_CUSTOMER_SUBMITTED";
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS";
export const CREATE_CUSTOMER_ERROR = "CREATE_CUSTOMER_ERROR";

export const CREATE_PAYMENT_SUBMITTED = "CREATE_PAYMENTR_SUBMITTED";
export const CREATE_PAYMENT_SUCCESS = "CREATE_PAYMENT_SUCCESS";
export const CREATE_PAYMENT_ERROR = "CREATE_PAYMENT_ERROR";